SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I
RIGHT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

-- # SELECT ANIMAL_ID, NAME
-- # FROM ANIMAL_OUTS
-- # WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
-- #                        FROM ANIMAL_INS)
-- # ORDER BY ANIMAL_ID;