WITH RECURSIVE generations AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT e.ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN generations g
    ON e.PARENT_ID = g.ID
)
SELECT COUNT(g.ID) AS COUNT, g.GENERATION
FROM generations g
LEFT JOIN ECOLI_DATA c
ON g.ID = c.PARENT_ID
WHERE c.ID IS NULL -- 자식이 없는 것만
GROUP BY g.GENERATION
ORDER BY g.GENERATION;